name: robot-nav-slam
channels:
  - https://conda.anaconda.org/robostack-staging
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - setuptools>=61
  - numpy>=1.24,<2
  - opencv=4.9
  - pyserial>=3.5
  - ros2-distro-mutex=0.5
  - ros-humble-ros-base
  - ros-humble-rclpy
  - ros-humble-nav-msgs
  - ros-humble-sensor-msgs
  - ros-humble-geometry-msgs
  - ros-humble-tf2-ros
  - ros-humble-cv-bridge
  - ros-humble-librealsense2=2.54.1
  - ros-humble-realsense2-camera=4.54.1
  - ros-humble-depthimage-to-laserscan=2.5.1=py311h5fd4792_6
  - ros-humble-slam-toolbox
  - ceres-solver=2.2.0=cpu*
  - pip:
      - pyrealsense2==2.54.1.5217
